server:
  port: ${SERVER_PORT}
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  error:
    include-message: always
    include-binding-errors: always
spring:
  config:
    import: optional:file:.env
  task:
    scheduling:
      pool:
        size: 4
    fixedDelay:
      value: 5000

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
  liquibase:
    analytics-enabled: true
    enabled: true
    change-log: ${LIQUIBASE_CHANGELOG_PATH}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  application:
    name: ${APPLICATION_NAME}
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cache:
    redis:
      time-to-live: ${REDIS_CACHE_TTL_SECONDS}
      use-key-prefix: true
      cache-null-values: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    listener:
      ack-mode: batch
custom:
  kafka:
    topics:
      account-created: account.created
      account-banned: account.banned
      account-deleted: account.deleted
      account-unbanned: account.unbanned
      account-updated: account.updated
  cache:
    redis:
      account-cache-name: account
      accounts-cache-name: accounts
      cache-ttl: 30s



